#!/usr/bin/env Rscript
# CLI for QC-Visualization module

suppressPackageStartupMessages({
  library(argparse)
  library(multiEpiCore)
})


parser <- ArgumentParser(
  prog = "qc_visualization_cli.R",
  description = "Visualize QC results from qc step (all_read_count.tsv + filtered_read_count.tsv) and generate heatmap"
)

# Required arguments
parser$add_argument(
  "--all_read_count_path",
  required = TRUE,
  help = "Path to all_read_count.tsv generated by qc_count.sh"
)

parser$add_argument(
  "--filtered_read_count_path",
  required = TRUE,
  help = "Path to filtered_read_count.tsv generated by qc_count.sh"
)

parser$add_argument(
  "--out_dir",
  required = TRUE,
  help = "Output directory for the heatmap PDF"
)

# Optional arguments
parser$add_argument(
  "--split_pair_by",
  default = "-",
  help = "Delimiter for splitting CRF pairs (default: '-')"
)

parser$add_argument(
  "--group_csv",
  default = NULL,
  help = "Optional CSV file with CRF grouping info"
)

parser$add_argument(
  "--crf_col",
  default = "crf",
  help = "Column name for CRF identifiers in group CSV (default: crf)"
)

parser$add_argument(
  "--category_col",
  default = "category",
  help = "Column name for CRF categories in group CSV (default: category)"
)

args <- parser$parse_args()


tryCatch({

  # Basic checks
  if (!file.exists(args$all_read_count_path)) {
    stop(paste0("File not found: ", args$all_read_count_path))
  }
  if (!file.exists(args$filtered_read_count_path)) {
    stop(paste0("File not found: ", args$filtered_read_count_path))
  }

  qc_visualization(
    all_read_count_path = args$all_read_count_path,
    filtered_read_count_path = args$filtered_read_count_path,
    out_dir = args$out_dir,
    split_pair_by = args$split_pair_by,
    group_csv = args$group_csv,
    crf_col = args$crf_col,
    category_col = args$category_col
  )

}, error = function(e) {
  message("ERROR: ", conditionMessage(e))
  quit(status = 1)
})
